function textRecognizer(inputImage)
% Launch an interactive UI for OCR (character/text recognition)
%
% SYNTAX:
%
% textRecognizer
%    Launches the textRecognizer app with the default image pre-loaded.
%
% textRecognizer(inputImage)
%    Allows user to specify input image, or the name of an
%    input image.
%
% textRecognizer(inputImage,roi)
%    Allows user to specify one or more rectangular region of interest
%    defined by an M-by-4 matrix, roi. Each row of roi is a four-element
%    vector, [x y width height], that specifies the upper-left corner and
%    size of a rectangular region of interest in pixels. Each rectangle
%    must be fully contained within I.
%
% textRecognizer(...,Name,Value) allows the specification of additional
%    name-value pair arguments described below:
%
%    'TextLayout'    Specify the layout of the text within I as a string.
%                    Valid string values are 'Auto', 'Block', 'Line', or
%                    'Word'. Default: 'Auto'
%
%    'Language'      Specify the language to recognize as a string or a
%                    cell array of strings. The language can be specified
%                    using the name of a language such as 'English' or
%                    'Japanese'.  Default: 'English'
%
%                    NOTES: A list of supported languages is shown in the
%                    documentation. Custom trained languages are also
%                    supported. Some language files have a dependency on
%                    another language. For example, Hindi training depends
%                    on English. If you want to use Hindi, the English
%                    traineddata file must also exist in the same folder as
%                    the Hindi traineddata file. You can download Tesseract
%                    3.02 language data files to use with the ocr function
%                    from the tesseract-ocr website.
%
%                    To use the ocr function with the downloaded language
%                    zipped files, you must unzip all files.
%
%    'CharacterSet'  Specify the character set as a string of characters.
%                    The classification process is constrained to select
%                    the best matches from this smaller set of characters.
%                    Default: Uses all characters in the Language.
%
% ocrResults = textRecognizer(...)
%    Outputs the result of the final scan. (Note that results can also be
%    exported from within the app.)
%
%    NOTE: To reset CharacterSets or Languages, edit OCRUserOpts (in the
%    same directory as textRecognizer), or delete it and it will be
%    regenerated with default values.
%
% (Note that OUTPUTS are supported via an "EXPORT" button.)
%
% EXAMPLE USAGE:
% %% Example 1:
% textRecognizer 
%    %(Launches UI with default 'GettysburgAddressEnglish.png' image.)
% 
% %% Example 2:
% textRecognizer('handicapSign.jpg')
%    %(Launches UI with user-defined image.)
% 
% %% Example 3:
% languageImage = imread('posters.jpg');
% textRecognizer(languageImage)
%    %(Launches UI with user-defined image.)
% 
%
% CLASS SUPPORT: The input image inputImage can be logical, uint8, int16,
% uint16, single, or double, and it must be real and nonsparse.
%
% Written by Brett Shoelson, PhD
% brett.shoelson@mathworks.com
% 7/24/2014
% Comments and suggestions welcome!
%
% See Also: ocr ocrText ocrText/locateText visionSupportPackages
% insertShape insertText doesImageContainText

% MODIFICATIONS:
% 11/19/2015: Fixed output display to capture preprocessing steps, and
%   to handle single quotes in the character set automatically.
%
% Copyright 2014 MathWorks, Inc.

if verLessThan('vision','6.0')
	error('SORRY! textRecognizer (and OCR) requires Computer Vision System Toolbox Ver. 6.0 (MATLAB R2014a) or later!');
end

% Initializations/Setup
if nargin < 1 || isempty(inputImage)
	%fname = 'businessCard.png';
	fname = 'GettysburgAddressEnglish.png';
	inputImage = imread('GettysburgAddressEnglish.png');
elseif ischar(inputImage)
	fname = inputImage;
	inputImage = imread(inputImage);
else
	fname = 'Original';
end
buttonColor = [0.55 0.65 0.65];
bgc = buttonColor*1.3;
fgc = imcomplement(bgc);
tbc = 240/255; %toolbar color, approximately
resizeValue = 5; %For autoresize
multiplier = 1;
workingImage = [];
[bboxes,ocrResults,OCRUserOpts,ROI] = deal([]);
[characterSetIndex,languageIndex] = deal(1);
pathToFile = mfilename('fullpath');
pathToFile = fileparts(pathToFile);
useFullFrame = true;
processString = '';
fpath = pwd;

% LAYOUT
axBottom = 0.325;
axTop = 0.95;
labelY = axBottom - 0.1;
controlTop = labelY - 0.0125;
controlBottom = 0.0875;
hgap = 0.01;
vgap = 0.0025;
lEdge = 0.025;
rEdge = 0.975;
textAlignment = 'left';
[objpos,objdim] = distributeObjects(7,lEdge,rEdge,hgap);
[vobjpos,vobjdim] = distributeObjects(4,controlBottom,controlTop,vgap);

% Load settings
getOCRUserOpts;
%
% To allow multiple simultaneous instances, change 'singleton' to false:
singleton = true;
if singleton
	delete(findall(0,'type','figure','name','textRecognizer'))
end

% SETUP
% FIGURE
textRecognizerFig = figure(...
	'numbertitle','off',...
	'windowstyle','normal',...
	'name','textRecognizer',...
	'units','Normalized',...
	'Position',[0.01 0.05 0.98 0.85],...
	'color',bgc,...
	'tag','textRecognizerFig',...
	'menubar','none',...
	'CloseRequestFcn',@closeFig);
textRecognizerFigHndl = textRecognizerFig;
set(textRecognizerFig,...
	'defaultuicontrolunits','Normalized',...
	'defaultuicontrolbackgroundcolor',bgc,...
	'defaultuicontrolfontsize',9);
% UITOOLBAR
ht = uitoolbar(textRecognizerFig);
tmp = im2double(imread('file_open.png'));
tmp(tmp==0) = NaN;
loadImageTool = uitoggletool(ht,...
	'CData', tmp,...
	'oncallback', @GetNewFile,...
	'offcallback', '',...
	'Tooltipstring', 'Load new image',...
	'Tag', 'loadImageTool'); %#ok<*NASGU>
tmp = im2double(imread('tool_zoom_in.png'));
tmp(tmp==0) = NaN;
zoomTool = uitoggletool(ht,...
	'CData', tmp,...
	'oncallback', @toggleZoom,...
	'offcallback', '',...
	'state','off',...
	'Tooltipstring', 'Toggle zoom state',...
	'separator', 'on');
icon = im2double(imread('tool_hand.png'));
icon(icon==0) = NaN;
uitoggletool(ht,...
	'CData', icon,...
	'ClickedCallback', @panIt,...
	'tooltipstring', 'Toggle panning');
addROIIcon = imread('addROI.png');
uitoggletool(ht,...
	'CData', addROIIcon,...
	'oncallback', @defineROI,...
	'tag', 'DefineROITool',...
	'state','off',...
	'tooltipstring', 'Add bounding box (ROI) for text recognition',...
	'separator', 'on');
icon = imread('deleteROIs.png');
uitoggletool(ht,...
	'CData', icon,...
	'state','off',...
	'oncallback', @deleteAllROIs,...
	'tooltipstring', 'Delete ALL ROI(s)');
tmp = imread('tooltipIcon2.png');
toggleTooltipButton = uitoggletool(ht,...
    'CData', tmp,...
    'tag','toggleTooltips',...
    'separator', 'off',...
	'state','off',...
    'oncallback', @toggleTooltipCB,...
    'Tooltipstring', 'Toggle tooltips on or off.',...
	'separator', 'on');
icon = imread('ocrIcon.png');
uitoggletool(ht,...
	'CData', icon,...
	'tag','RecognizeButton',...
	'ClickedCallback', @processOCR,...
	'separator', 'on',...
	'state','off',...
	'tooltipstring', 'Recognize text using current settings/selections');
icon = imread('matlabicon.png');
uitoggletool(ht,...
	'CData', icon,...
	'oncallback', @acknowledge,...
	'Tooltipstring', 'Acknowledgements',...
	'separator', 'on');
% AXES/IMAGE
ImageAxis = axes(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[lEdge axBottom 0.6 axTop-axBottom ],...
	'Color',bgc,...
	'Tag','ImageAxis',...
	'XLimMode','auto',...
	'YLimMode','auto',...
	'Visible','off');
ImgObj = imshow(inputImage,'parent',ImageAxis);
ImgTitle = title(fname,'interpreter','none',...
	'fontweight','bold',...
	'color',fgc);
expandAxes(ImageAxis);
% RESULTS PANEL
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[0.675 axTop+0.01 rEdge-0.675 0.03],...
	'String','Text Results',...
	'Style','text',...
	'fontweight','bold',...
	'fontsize',11,...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
tmp = lEdge+0.6+hgap*5;
resultsPanel = uicontrol(textRecognizerFig,...
	'style','listbox',...
	'min',0,...
	'max',10,...
	'horizontalalignment','left',...
	'units','normalized',...
	'position',[tmp axBottom rEdge-tmp axTop-axBottom],...
	'backgroundcolor','w',...
	'string',[]);
%
% UICONTROLS
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(1) labelY objdim 0.02],...
	'String','TEXT LAYOUT',...
	'Style','text',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
layoutListbox = uicontrol(...
	'Parent',textRecognizerFig,...
	'style','listbox',...
	'Tag','LayoutPanel',...
	'Units','Normalized',...
	'Position',[objpos(1) vobjpos(1) objdim controlTop-controlBottom],...
	'string',char({'AUTO','Block','Line','Word'}),...
	'callback',@processOCR);
% LANGUAGE
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(2) labelY objdim 0.02],...
	'String','LANGUAGE',...
	'Style','text',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
language = 'English'; % Default
allLanguages = char(cat(1,{OCRUserOpts.Language}','Other'));
languageListbox = uicontrol(...
	'Parent',textRecognizerFig,...
	'style','listbox',...
	'Tag','LanguagePanel',...
	'Units','Normalized',...
	'Position',[objpos(2) controlBottom objdim controlTop-controlBottom],...
	'string',allLanguages,...
	'callback',@verifyLanguage);
% CHARACTER SET
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(3) labelY objdim 0.02],...
	'String','CHARACTER SET',...
	'Style','text',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
characterSet = char(32:255); % Default
characterListbox = uicontrol(...
	'Parent',textRecognizerFig,...
	'style','listbox',...
	'Tag','LanguagePanel',...
	'Units','Normalized',...
	'Position',[objpos(3) controlBottom objdim controlTop-controlBottom],...
	'string','',...
	'callback',@verifyCharacterSet);
% MANUALLY SPECIFY BOUNDING BOXES
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(4) labelY objdim 0.02],...
	'String','ROI SPECIFICATION',...
	'Style','text',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
% autoDetectROIButton = uicontrol(...
% 	'Parent',textRecognizerFig,...
% 	'Callback',@autoDetectROIs,...
% 	'FontSize',9,...
% 	'Units','Normalized',...
% 	'Position',[objpos(4) vobjpos(3) objdim vobjdim],...
% 	'String','Auto-Detect ROIs',...
% 	'tooltipstring','Attempt to automatically determine text bounding boxes.',...
% 	'fontweight','bold',...
% 	'foregroundcolor',fgc,...
% % 	'enable','on');
uicontrol(...
	'Parent',textRecognizerFig,...
	'Callback',@defineROI,...
	'FontSize',9,...
	'Units','Normalized',...
	'Position',[objpos(4) vobjpos(2) objdim vobjdim],...
	'String','Add Manual ROI',...
	'tooltipstring','Constrain ocr by specifying bounding box(es).',...
	'fontweight','bold',...
	'foregroundcolor',fgc);
uicontrol(...
	'Parent',textRecognizerFig,...
	'Callback',@deleteAllROIs,...
	'FontSize',9,...
	'Units','Normalized',...
	'Position',[objpos(4) vobjpos(1) objdim vobjdim],...
	'String','Delete All ROIs',...
	'tooltipstring','Remove bounding-box constraints from ocr.',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'Tag','ExportButton');
% PROCESS OPTIONS
autoPreprocessCheckbox = uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(5) vobjpos(3) objdim vobjdim],...
	'String','Auto-Preprocess',...
	'value',0,...
	'Style','checkbox',...
	'tooltipstring','Attempt to improve results by automaticaly preprocessing the image. (Results may be improved at the expense of performance.)',...
	'callback',@processOCR);
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(5) labelY objdim 0.02],...
	'String','PROCESS OPTIONS',...
	'Style','text',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
processImmediatelyCheckbox = uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(5) vobjpos(4) objdim vobjdim],...
	'String','Process Immediately',...
	'value',0,...
	'Style','checkbox',...
	'tooltipstring','All actions (except ROI definitions) trigger immediate text recognition.',...
	'callback',@processOCR);
RecognizeButton = uicontrol(...
	'Parent',textRecognizerFig,...
	'Callback',@processOCR,...
	'FontSize',9,...
	'Units','Normalized',...
	'Position',[objpos(5) vobjpos(2) objdim vobjdim],...
	'String','RECOGNIZE',...
	'tooltipstring','Recognize text using current settings/selections.',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'Tag','RecognizeButton');
%addDocButton(RecognizeButton,'ocr','lowerleft')
ExportButton = uicontrol(...
	'Parent',textRecognizerFig,...
	'Callback',@exportResults,...
	'FontSize',9,...
	'Units','Normalized',...
	'Position',[objpos(5) vobjpos(1) objdim vobjdim],...
	'String','Export Results',...
	'tooltipstring','Write results to base workspace.',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'Tag','ExportButton');
% HIGHLIGHTING OPTIONS
annotation('line',[objpos(6)-hgap/2,objpos(6)-hgap/2],[controlBottom,labelY+0.015],...
	'color', [1 1 0.6],...
	'linewidth',3)
annotation('line',[objpos(6)-hgap/2,objpos(6)-hgap/2],[controlBottom,labelY+0.015],...
	'color',fgc*1.7,...
	'linewidth',3,...
	'linestyle','--');
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(6) labelY objdim 0.02],...
	'String','TEXT-HIGHLIGHT OPTIONS',...
	'Style','text',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
useRegexpCheckbox = uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(6) vobjpos(3) objdim vobjdim],...
	'String','Use Regexp',...
	'tooltipstring','Use Regular Expressions',...
	'value',0,...
	'Style','checkbox');
ignoreCaseCheckbox = uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(6) vobjpos(2) objdim vobjdim],...
	'String','Ignore Case',...
	'value',0,...
	'Style','checkbox');
highlightTextButton = uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(6) vobjpos(1) objdim vobjdim],...
	'String','Highlight Text',...
	'value',0,...
	'fontweight','bold',...
	'backgroundcolor',[1 1 0.7],...
	'foregroundcolor',fgc,...
	'tooltipstring','Locate and highlight specified text in original image.',...
	'Style','pushbutton',...
	'callback',@highlightText);
% DOC/EXAMPLES LINKS
annotation('line',[objpos(7)-hgap/2,objpos(7)-hgap/2],[controlBottom,labelY+0.015],...
	'color', [1 1 0.6],...
	'linewidth',3)
annotation('line',[objpos(7)-hgap/2,objpos(7)-hgap/2],[controlBottom,labelY+0.015],...
	'color',fgc*1.7,...
	'linewidth',3,...
	'linestyle','--');
uicontrol(...
	'Parent',textRecognizerFig,...
	'Units','Normalized',...
	'Position',[objpos(7) labelY-0.02 objdim 0.04],...
	'String',sprintf('DOCUMENTATION &\nEXAMPLES'),...
	'Style','text',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'HorizontalAlignment',textAlignment);
uicontrol(...
	'Parent',textRecognizerFig,...
	'Callback','doc(''ocr'')',...
	'FontSize',9,...
	'Units','Normalized',...
	'Position',[objpos(7) vobjpos(2) objdim vobjdim],...
	'String','OCR Documentation',...
	'fontweight','bold',...
	'foregroundcolor',fgc);
uicontrol(...
	'Parent',textRecognizerFig,...
	'Callback','web(fullfile(docroot, ''vision/examples/recognize-text-using-optical-character-recognition-ocr.html''))',...
	'FontSize',9,...
	'Units','Normalized',...
	'Position',[objpos(7) vobjpos(1) objdim vobjdim],...
	'String','OCR Examples',...
	'fontweight','bold',...
	'foregroundcolor',fgc,...
	'Tag','ExportButton',...
	'Enable','on');
% COMMENTS
CommentsPanel = uipanel(...
	'Parent',textRecognizerFig,...
	'Title','Comments/Status',...
	'Tag','CommentsPanel',...
	'Units','Normalized',...
	'Position',[objpos(1) 0.015 rEdge-objpos(1) controlBottom-0.01-0.015]);
CommentsBox = uicontrol(...
	'Parent',CommentsPanel,...
	'Style','Edit',...
	'String','Welcome to textRecognizer! © 2014 The MathWorks, Inc.',...
	'Tag','CommentsBox',...
	'Units','Normalized',...
	'Fontsize',10,...
	'min',0,...
	'max',10,...
	'Position',[0 -0.01 1 1.06],...
	'Enable','Inactive');
%
verifyLanguage;
%
bgsAndPanels = [findobj(textRecognizerFig,'type','uibuttongroup');
	findobj(textRecognizerFig,'type','uipanel')];
set(bgsAndPanels,...
	'Units','Normalized',...
	'BorderType', 'etchedin',...
	'FontSize',8,...
	'ForegroundColor',[0 0 0],...
	'TitlePosition','lefttop',...
	'backgroundColor',bgc)

if isfield(OCRUserOpts,'processImmediatelyOption')
	set(processImmediatelyCheckbox,...
		'value',OCRUserOpts(1).processImmediatelyOption);
end
if isfield(OCRUserOpts,'preprocessOption')
	set(autoPreprocessCheckbox,...
		'value',OCRUserOpts(1).preprocessOption);
	updateWorkingImage;
end

set(textRecognizerFig,'Handlevisibility','callback');

if ~nargout
	clear textRecognizerFigHndl
end
% %%% BEGIN NESTED SUBFUNCTIONS
%
	function acknowledge(varargin)
		mssg = {'',...
			'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ',...
			'',...
			'I would like to acknowledge and thank the following for',...
			'suggestions, reviews, and critiques of this tool:',...
			'',...
			'Witek Jachimczyk',...
			'Birju Patel',...
			'The Computer Vision System Toolbox Development Team',...
			'',...
			'Comments and suggestions are welcome,',...
			'and should be addressed to me at:',...
			'',...
			'brett.shoelson@mathworks.com',...
			'',...
			'© 2014 MathWorks, Inc.',...
			'',...
			'',...
			'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',...
			''};
		h = msgbox(mssg,'textRecognizer Acknowledgments','help','modal') ;
		msghndl = findobj(h,'tag','MessageBox');
		set(msghndl,'color',[0 0 0.7],'fontweight','b','fontname','helvetica')
		set(gcbo,'state','off')
	end %acknowledge

% 	function autoDetectROIs(varargin)
% 		tmp = 'CONTINUE';
% 		if numel(workingImage) > 1500^2
% 			warnstr = 'WARNING: PROCEED AT YOUR OWN RISK! This may be VERY slow given the size of your (preprocessed?) image!';
% 			tmp = questdlg(warnstr,'Slow Warning','CONTINUE','Never Mind','CONTINUE');
% 		elseif numel(workingImage) > 640*480
% 			warnstr = 'Warning: This may be a bit slow...';
% 			tmp = questdlg(warnstr,'Slow Warning','CONTINUE','Never Mind','CONTINUE');
% 		end
% 		if ~strcmp(tmp,'CONTINUE')
% 			return
% 		end
% 		set(CommentsBox,'string','Attempting to discover light-on-dark text regions...please wait.');
% 		drawnow;
% 		% Try both bright and dark?
% 		opts = {'LightTextOnDark','DarkTextOnLight'};
% 		bboxesBright = [];
% 		bboxesDark = [];
% 		try
% 			bboxesBright = autoDetectText(workingImage,'TextPolarity',opts{1});%inputImage
% 		end
% 		set(CommentsBox,'string','Attempting to discover dark-on-light text regions...please wait.');
% 		drawnow;
% 		try
% 			bboxesDark = autoDetectText(workingImage,'TextPolarity',opts{2});%inputImage
% 		end
% 		%bboxesBright = detectText(inputImage,'bright');
% 		%bboxesDark = detectText(inputImage,'dark');
% 		if ~isempty(bboxesBright)||~isempty(bboxesDark)
% 			for ii = 1:size(bboxesBright,1)
% 				ROI = [ROI;addROI(ImageAxis,bboxesBright(ii,:))];%#ok
% 			end
% 			for ii = 1:size(bboxesDark,1)
% 				ROI = [ROI;addROI(ImageAxis,bboxesDark(ii,:))];%#ok
% 			end
% 			processOCR;
% 			set(CommentsBox,'string','Auto-detected bounding box(es) marked in image above.');
% 		else
% 			set(CommentsBox,'string','Unable to auto-detect text regions in this image.');
% 		end
% 	end

	function closeFig(varargin)
		OCRUserOpts(1).processImmediatelyOption = get(processImmediatelyCheckbox,'value');
		OCRUserOpts(1).preprocessOption = get(autoPreprocessCheckbox,'value');
		save(fullfile(pathToFile,'ocrUserOpts.mat'),'OCRUserOpts')
		closereq;
	end %closeFig

	function defineROI(varargin)
		try % if called from menubar
			set(gcbo,'state','off');
		end
		axes(ImageAxis)
		oldString = get(ImgTitle,'string');
		set(ImgTitle,...
			'string','Drag cursor to define ROI.');
		ROI = [ROI;addROI];
		set(ImgTitle,...
			'string',oldString);
		if isempty(ROI)
			return
		end
	end %defineROI

	function deleteAllROIs(varargin)
		try
			set(gcbo,'state','off')
		end
		if nargin == 0 || (nargin > 0 && ishandle(varargin{1}))
			opt = 'Verify';
		else
			opt = varargin{1};
		end
		% Delete ALL ROIs
		if strcmp(opt,'Verify')
			verified = verifyCommand('Pressing CONTINUE will remove all ROIs this image!');
		else
			verified = true;
		end
		if verified
			delete(findall(gcf,'tag','delButton'))
			delete(ROI)
			ROI = [];
		end
	end %deleteAllROIs

	function exportResults(varargin)
		if isempty([ocrResults.Text])
			set(CommentsBox,'string',...
				'You must first successfully recognize some text before you export results!');
			return
		end
		n = 0; tmp = 1;
		while tmp
			n = n + 1;
			tmp = evalin('base',['exist(''ocrResults', num2str(n), ''')']);
		end
		set(CommentsBox,'string',sprintf('Current results written to ocrResults%d in Base (Command-Line) Workspace.\nReproduction code written to MATLAB Command Line.',n));
		assignin('base',['ocrResults' num2str(n)],ocrResults);
		%disp(ocrResults)
		fprintf('Current results written to ocrResults%d in Base (Command-Line) Workspace\n\n',n);
		% GENERATE CODE!
		fprintf('\nREPRODUCTION STEPS:\n******************\n')
		if size(workingImage,3)==3
			disp('inputImage = rgb2gray(inputImage);')
		end
		if multiplier ~= 1
			fprintf('inputImage = imresize(inputImage,%i);\n',multiplier);
		end
		if get(autoPreprocessCheckbox,'value')
			disp('inputImage = medfilt2(inputImage);')
			disp('inputImage = imadjust(inputImage);')
		end
		if useFullFrame
			fprintf('bboxes = [1 1 size(inputImage,2) size(inputImage,1)];\n');
		else
			fprintf('bboxes = \t[\n');
			%fprintf('\t%0.3f\t\t%0.3f\t\t%0.3f\t\t%0.3f',bboxes');
			disp(bboxes);
			fprintf('\t\t\t];\n%%\n')
		end
		disp(processString)
		fprintf('******************\n')
	end %exportResults

	function GetNewFile(varargin)
		set(gcbo,'state','off');
		currPath = pwd;
		cd(fpath);
		[img,cmap,fname,fpath,userCanceled] = getNewImage(false);
		cd(currPath);
		if userCanceled
			return
		end
		ocrResults = [];
		bboxes = [];
		ROI = [];
		if ~isempty(cmap)
			inputImage = ind2rgb(img,cmap);
		else
			inputImage = img;
		end
		cla(ImageAxis);
		ImgObj = imshow(inputImage,'parent',ImageAxis); %#ok
		originalImg = imshow(img,'parent',ImageAxis);
		expandAxes(ImageAxis);
		ImgTitle = title(fname,'interpreter','none',...
			'fontweight','bold',...
			'color',fgc);
		set(ImageAxis,'XLim',0.5+[0 size(img,2)],'YLim',0.5+[0 size(img,1)]);
		processOCR
	end %GetNewFile

	function getOCRUserOpts
		% ALL OCRUserOpts should be Nx1-cell-array format
		if exist(fullfile(pathToFile,'ocrUserOpts.mat'),'file')
			OCRUserOpts = load(fullfile(pathToFile,'ocrUserOpts.mat'));
			OCRUserOpts = OCRUserOpts.OCRUserOpts;
		else
			OCRUserOpts(1).Language = 'English';
			OCRUserOpts(1).CharacterSet = {'All Characters';'Alpha Only';'Numeric Only'};
			%char(32:126);
			OCRUserOpts(1).CharacterValues = {char(32:126);char([65:90,97:122]);'1234567890'};
			OCRUserOpts(2).Language = 'Japanese';
			OCRUserOpts(2).CharacterSet = {'All Characters'};
			%OCRUserOpts(2).CharacterValues = {native2unicode(135:234,'Shift_JIS')};
			OCRUserOpts(2).CharacterValues = {native2unicode(135:234,'Shift_JIS')};
			save(fullfile(pathToFile,'ocrUserOpts.mat'),'OCRUserOpts')
		end
	end %getOCRUserOpts

	function highlightText(varargin)
		if isempty(ocrResults)
			set(CommentsBox,'string','You must first successfully recognize some text before you try to highlight it!');
			return
		end
		delete(findobj(textRecognizerFig,'tag','highlightPatch'));
		textToSeek = inputdlg('Enter text to seek                                                           :',...
			'Search String',1,{'people'});
		if isempty(textToSeek)
			return
		end
		bboxes = locateText(ocrResults,textToSeek{1},...
			'UseRegexp',get(useRegexpCheckbox,'value'),...
			'IgnoreCase',get(ignoreCaseCheckbox,'value'));
		bboxes = (bboxes+multiplier-1)/multiplier;
		%bboxes = multiplier*bboxes-multiplier+1;
		currHold = ishold;
		hold on
		for ii = 1:size(bboxes,1)
			tmp = bboxes(ii,:);
			xs = [tmp(1) tmp(1)+tmp(3) tmp(1)+tmp(3) tmp(1) tmp(1)];
			ys = [tmp(2) tmp(2) tmp(2)+tmp(4) tmp(2)+tmp(4) tmp(2)];
			patch(xs,ys,'y','FaceAlpha',0.5,'tag','highlightPatch','EdgeColor','none')
		end
		if ~currHold
			hold off
		end
	end %highlightText

	function processOCR(varargin)
		updateWorkingImage;
		cboTag = '';
		ocrResults = [];
		ocrResults(1).Text = '';
		try %If processing is from Default-Reset, there is no input argument
			cboTag = get(varargin{1},'tag');
			set(gcbo,'state','off');
		end
		processImmediately = get(processImmediatelyCheckbox,'value');
		if processImmediately || strcmp(cboTag,'RecognizeButton');
			delete(findobj(textRecognizerFig,'tag','highlightPatch'));
			set(CommentsBox,'string','Processing...please wait.');
			set(resultsPanel,'string','');
			drawnow;
			% Text Layout:
			textLayout = get(layoutListbox,'string');
			textLayout = deblank(textLayout(get(layoutListbox,'value'),:));
			% Bounding Boxes:
			bboxes = [];
			ind = 0;
			for ii = 1:numel(ROI)
				% We put this in a try/catch loop because ROIs may have
				% been deleteted
				try
					tmpPos = ROI(ii).getPosition;
					ind = ind+1;
					bboxes(ind,:) = tmpPos;
				end
			end
			if isempty(bboxes)
				% Full-frame
				useFullFrame = true;
				bboxOpt = '(full-frame)';
				bboxes = [1 1 size(inputImage,2) size(inputImage,1)];
			else
				useFullFrame = false;
				bboxOpt = '(user-defined)';
			end
			bboxes = multiplier*bboxes-multiplier+1;
			characterSet = OCRUserOpts(languageIndex).CharacterValues{characterSetIndex};
				try
					ocrResults = ocr(workingImage,...
						bboxes,...
						'TextLayout',textLayout,...
						'Language',language,...
						'CharacterSet',characterSet);
					characterSet = regexprep(characterSet,'''','''''');
					processString = sprintf('ocrResults = ocr(inputImage,bboxes,...\n\t''TextLayout'',''%s'',...\n\t''Language'',''%s'',...\n\t''CharacterSet'',''%s'');',...
						textLayout,language,characterSet);
				catch exception
					set(CommentsBox,'string','Character recognition unsuccessful with these parameters.');
					tmp = exception.message;
					errordlg(sprintf('%s',tmp))
				end
			if ~isempty(ocrResults(1).Text)
				set(CommentsBox,'string',sprintf('Processing complete, using %i %s ROI(s). Use ''Export Results'' button to write full results to base workspace. (''recognizedText'' automatically written.)',size(bboxes,1),bboxOpt));
				set(resultsPanel,'string',[ocrResults.Text]);
				if numel(ocrResults) == 1
						assignin('base','recognizedText',ocrResults.Text);
				else
					for jj = 1:numel(ocrResults)
						assignin('base',['recognizedText' num2str(jj)],ocrResults(jj).Text);
					end
				end
			else
				set(CommentsBox,'string',sprintf('Processing complete, using %i %s ROI(s). NO TEXT DETECTED!',size(bboxes,1),bboxOpt));
			end
		else
			return
		end
	end %processOCR

	function toggleTooltipCB(varargin)
		set(gcbo,'state','off');
		status = toggleTooltips(textRecognizerFig);
		set(CommentsBox,'string',sprintf('Tooltips turned %s.',status));
		set(toggleTooltipButton,...
			'Tooltipstring', 'Toggle tooltips on or off.');
	end %toggleTooltipCB

	function toggleZoom(varargin)
		zoom(textRecognizerFig);
		set(gcbo,'state','off');
	end %toggleZoom

	function updateWorkingImage(varargin)
		multiplier = (resizeValue-1)*double(get(autoPreprocessCheckbox,'value'))+1;
		workingImage = inputImage;
		if size(workingImage,3)==3
			workingImage = rgb2gray(workingImage);
		end
		workingImage = imresize(workingImage,multiplier);
		if get(autoPreprocessCheckbox,'value')
			workingImage = medfilt2(workingImage);
		end
		if get(autoPreprocessCheckbox,'value')
			workingImage = imadjust(workingImage);
		end
	end %updateWorkingImage

	function verifyCharacterSet(varargin)
		% CharacterSet:
		characterSet = get(characterListbox,'string');
		characterSet = deblank(characterSet(get(characterListbox,'value'),:));
		if strcmp(characterSet,'Custom')
			newCharacterSet = inputdlg({'Enter characters to include:                                                  :',...
				'Enter a name for this set, if you would like to save it:'},'New Character Set',1,{'0123456789','DigitsOnly'});
			if isempty(newCharacterSet)
				set(characterListbox,'value',characterSetIndex);
				return
			end
			newCharacterSetVal = newCharacterSet{1};
			characterSet = newCharacterSetVal;
			newCharacterSetName = newCharacterSet{2};
			if ~isempty(newCharacterSetName) && ischar(newCharacterSetName)
				OCRUserOpts(languageIndex).CharacterSet = cat(1,OCRUserOpts(languageIndex).CharacterSet,{newCharacterSetName});
				OCRUserOpts(languageIndex).CharacterValues = cat(1,OCRUserOpts(languageIndex).CharacterValues,{newCharacterSetVal});
				tmpCharSet = char(cat(1,OCRUserOpts(languageIndex).CharacterSet,{'Custom'}));
				set(characterListbox,...
					'string',tmpCharSet);
				save(fullfile(pathToFile,'ocrUserOpts.mat'),'OCRUserOpts')
				set(CommentsBox,'string',sprintf('''%s'' has been added to your character set list, and will persist in future sessions.\nTo reset the character-set list, remove file ''ocrUserOpts.mat'' from %s. (It will auto-generate, but you will lose customizations.)',...
					newCharacterSetName,userpath));
			end
		end
		characterSetIndex = get(characterListbox,'value');
		processOCR;
	end %verifyCharacterSet

	function verified = verifyCommand(verifyString)
		verified = questdlg(verifyString,...
			'!! Warning !!','CONTINUE','Cancel','CONTINUE');
		verified = strcmp(verified,'CONTINUE');
	end %verifyCommand

	function verifyLanguage(varargin)
		previousLanguage = language;
		% Language:
		language = get(languageListbox,'string');
		language = deblank(language(get(languageListbox,'value'),:));
		if ~strcmp(language,previousLanguage)
			set(characterListbox,'value',1)
			characterSetIndex = 1;
		end
		if strcmp(language,'Other')
			languageToAdd = inputdlg('Enter name of new language                               :',...
				'New Language',1,{''});
			if isempty(languageToAdd)
				set(languageListbox,...
					'value',languageIndex);
				language = previousLanguage;
				return
			end
			languageToAdd = languageToAdd{1};
			language = languageToAdd;
			currentLanguages = {OCRUserOpts.Language}';
			if ~ismember(languageToAdd,currentLanguages)
				tmp = questdlg(sprintf('Would you like to add %s to your list of languages?',languageToAdd),...
					'Add Language?','YES','No','YES');
				if strcmp(tmp,'YES')
					OCRUserOpts(size(OCRUserOpts,2)+1).Language = languageToAdd;
					OCRUserOpts(size(OCRUserOpts,2)).CharacterSet = {'All Characters'};
					OCRUserOpts(size(OCRUserOpts,2)).CharacterValues = {char(32:255)};
					languageIndex = numel({OCRUserOpts.Language});
					allLanguages = char(cat(1,{OCRUserOpts.Language}','Other'));
					set(languageListbox,...
						'string',allLanguages,...
						'value',languageIndex);
					%set(characterListbox,'string',char(OCRUserOpts(languageIndex).CharacterSet))
					save(fullfile(pathToFile,'ocrUserOpts.mat'),'OCRUserOpts')
					set(CommentsBox,'string',sprintf('''%s'' has been added to your language list, and will persist in future sessions.\nTo reset the language list, remove file ''ocrUserOpts.mat'' from %s. (It will auto-generate, but you will lose customizations.)',languageToAdd,userpath));
					set(characterListbox,'string',char(cat(1,OCRUserOpts(languageIndex).CharacterSet,'Custom')))
				end
				% visionSupportPackages Launches the Support Package Installer,
				% where you will be able to download, and install support packages
				% for the Computer Vision System Toolbox.
				tmp = questdlg('Would you like to launch the Support Package Installer to download and install new language support packages?',...
					'Launch Vision Support Packages?','YES','No','YES');
				if strcmp(tmp,'YES')
					visionSupportPackages
				else
					warndlg('You will not be able to use this language until the support package for it is installed!')
				end
			else
				beep
				set(CommentsBox,'string','It appears that this language is already in your language list! (Request is being ignored.)')
			end
		else
			languageIndex = find(strcmp({OCRUserOpts.Language}',language));
			set(characterListbox,'string',char(cat(1,OCRUserOpts(languageIndex).CharacterSet,'Custom')))
		end
		processOCR;
	end %verifyLanguage

% %%% END NESTED SUBFUNCTIONS
end